PACKAGE=mootor
SRC_DIR=src
VERSION=` date "+%Y.%m%d" `
RELEASE_DIR=release
COPY_DIR=../../js
RELEASE_FILE= $(PACKAGE)-$(VERSION).js
RELEASE_FILE_MIN= $(PACKAGE)-$(VERSION).min.js
COPY_FILE=$(PACKAGE).js

all:
	@@echo "Building..."
	#@@cat $(SRC_DIR)/header.js $(SRC_DIR)/core.js $(SRC_DIR)/event.js $(SRC_DIR)/fx.js $(SRC_DIR)/nav.js $(SRC_DIR)/footer.js  > $(RELEASE_DIR)/$(RELEASE_FILE)
	@@echo "Build completed."


